// generated 2003/3/17 17:26:21 CET by christof@puck.petig-baender.de
// using glademm V1.1.3e_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/christof/cvs/common/Komponenten2/glade/Komponenten.glade
// for gtk 2.2.1 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ././IntStringPopup.cc

#include "config.h"
#include "IntStringPopup_glade.hh"

IntStringPopup_glade::IntStringPopup_glade(GlademmData *_data
)
{  
   
   Gtk::Menu *IntStringPopup = this;
   zurueck = NULL;
   
   IntStringPopup->items().push_back(Gtk::Menu_Helpers::MenuElem("Zurücksetzen"));
   zurueck = (Gtk::MenuItem *)&IntStringPopup->items().back();
   zurueck->show();
   IntStringPopup->show();
}

IntStringPopup_glade::~IntStringPopup_glade()
{  
}
