// $Id: KundenBox_glade.hh,v 1.2 2002/07/05 12:36:56 christof Exp $
/*  libKomponenten: GUI components for ManuProC's libcommon++
 *  Copyright (C) 2001 Adolf Petig GmbH & Co. KG, written by Jacek Jakubowski
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/2/12 17:15:08 CET by christof@puck.(none)
// using glademm V0.5_11e
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- Komponenten.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/KundenBox.hh and./src/KundenBox.cc

#ifndef _KUNDENBOX_GLADE_HH
#  define _KUNDENBOX_GLADE_HH

#include <gtk--/table.h>
#include <gtk--/label.h>
#include "SearchCombo.hh"
#include "SearchComboContent.hh"

class KundenBox_glade : public Gtk::Table
{   
protected:
        
        Gtk::Label *label_kdnr;
        Gtk::Label *label_nam;
        SearchCombo *kundennr;
        SearchComboContent<Kunde::ID> *kundenname;
        
        KundenBox_glade();
        
        ~KundenBox_glade();
};
#endif
