// generated 2005/9/7 12:02:28 CEST by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.8.3 and gtkmm 2.7.3
//
// Please modify the corresponding derived classes in ././WTelefon.hh and././WTelefon.cc

#ifndef _WTELEFON_GLADE_HH
#  define _WTELEFON_GLADE_HH

#include <gtkmm/table.h>
#include <gtkmm/optionmenu.h>
#include <gtkmm/entry.h>
#include <gtkmm/box.h>
#include <gtkmm/frame.h>
#include "SimpleTree.hh"
#include <gtkmm/viewport.h>

class WTelefon_glade : public Gtk::Table
{  
protected:
        
        class Gtk::OptionMenu * option_menu;
        class Gtk::Entry * _land;
        class Gtk::Entry * _vorwahl;
        class Gtk::Entry * _nummer;
        class Gtk::Entry * _durchwahl;
        class Gtk::HBox * telnummer_box;
        class Gtk::Entry * textfeld;
        class Gtk::Frame * text_box;
        class SimpleTree * tree;
        class Gtk::Viewport * viewport;
        
        WTelefon_glade();
        
        ~WTelefon_glade();
private:
        virtual void on_buttonNumLoeschen_clicked() = 0;
        virtual void anderer_typ() = 0;
        virtual void land_activate() = 0;
        virtual void vorwahl_activate() = 0;
        virtual void nummer_activate() = 0;
        virtual void durchwahl_activate() = 0;
        virtual void text_activate() = 0;
};
#endif
