// generated 2006/8/14 17:36:02 CEST by christof@vesta.petig-baender.de
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --noaccelerators Komponenten.glade
// for gtk 2.10.1 and gtkmm 2.9.10
//
// Please modify the corresponding derived classes in ././WTelefon.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "WTelefon_glade.hh"
#include <gtkmm/button.h>
#include <gtkmm/menu.h>
#include <gtkmm/box.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/scrolledwindow.h>
#ifndef ENABLE_NLS
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif


WTelefon_glade::WTelefon_glade(
) : Gtk::Table(2, 2, false)
{  
   
   Gtk::Table *WTelefon = this;
   Gtk::Button *button2 = Gtk::manage(new class Gtk::Button(_("Nummer löschen")));
   option_menu = Gtk::manage(new class Gtk::OptionMenu());
   
   Gtk::VBox *vbox_telnr = Gtk::manage(new class Gtk::VBox(false, 0));
   _land = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label9 = Gtk::manage(new class Gtk::Label(_("Land")));
   Gtk::Frame *frame2 = Gtk::manage(new class Gtk::Frame());
   _vorwahl = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label10 = Gtk::manage(new class Gtk::Label(_("Vorwahl")));
   Gtk::Frame *frame3 = Gtk::manage(new class Gtk::Frame());
   _nummer = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label11 = Gtk::manage(new class Gtk::Label(_("Nummer")));
   Gtk::Frame *frame4 = Gtk::manage(new class Gtk::Frame());
   _durchwahl = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label12 = Gtk::manage(new class Gtk::Label(_("Durchwahl")));
   Gtk::Frame *frame5 = Gtk::manage(new class Gtk::Frame());
   telnummer_box = Gtk::manage(new class Gtk::HBox(false, 0));
   
   Gtk::HBox *hbox10 = Gtk::manage(new class Gtk::HBox(false, 0));
   textfeld = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label13 = Gtk::manage(new class Gtk::Label(_("Text")));
   text_box = Gtk::manage(new class Gtk::Frame());
   
   Gtk::HBox *hbox11 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label8 = Gtk::manage(new class Gtk::Label(_("Neue Nummer eingeben")));
   Gtk::Frame *frame1 = Gtk::manage(new class Gtk::Frame());
   tree = new class SimpleTree(2);
   viewport = Gtk::manage(new class Gtk::Viewport(*manage(new Gtk::Adjustment(0,0,1)), *manage(new Gtk::Adjustment(0,0,1))));
   
   Gtk::ScrolledWindow *scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   button2->set_flags(Gtk::CAN_FOCUS);
   option_menu->set_flags(Gtk::CAN_FOCUS);
   {  
      
      Gtk::Menu *_m(manage(new Gtk::Menu()));
      Gtk::MenuItem *_mi;
      option_menu->set_menu(*_m);
      option_menu->set_history(0);
   }
   option_menu->set_history(-1);
   vbox_telnr->pack_start(*option_menu, Gtk::PACK_SHRINK, 0);
   _land->set_flags(Gtk::CAN_FOCUS);
   _land->set_text("");
   _land->set_width_chars(4);
   frame2->set_label_align(0,0.5);
   frame2->add(*_land);
   frame2->set_label_widget(*label9);
   _vorwahl->set_flags(Gtk::CAN_FOCUS);
   _vorwahl->set_text("");
   _vorwahl->set_width_chars(5);
   frame3->set_label_align(0,0.5);
   frame3->add(*_vorwahl);
   frame3->set_label_widget(*label10);
   _nummer->set_flags(Gtk::CAN_FOCUS);
   _nummer->set_text("");
   _nummer->set_width_chars(7);
   frame4->set_label_align(0,0.5);
   frame4->add(*_nummer);
   frame4->set_label_widget(*label11);
   _durchwahl->set_flags(Gtk::CAN_FOCUS);
   _durchwahl->set_text("");
   _durchwahl->set_width_chars(3);
   frame5->set_label_align(0,0.5);
   frame5->add(*_durchwahl);
   frame5->set_label_widget(*label12);
   telnummer_box->pack_start(*frame2);
   telnummer_box->pack_start(*frame3);
   telnummer_box->pack_start(*frame4);
   telnummer_box->pack_start(*frame5);
   hbox10->pack_start(*vbox_telnr, Gtk::PACK_SHRINK, 0);
   hbox10->pack_start(*telnummer_box);
   textfeld->set_flags(Gtk::CAN_FOCUS);
   textfeld->set_text("");
   text_box->set_label_align(0,0.5);
   text_box->add(*textfeld);
   text_box->set_label_widget(*label13);
   hbox11->pack_start(*text_box);
   vbox1->pack_start(*hbox10);
   vbox1->pack_start(*hbox11);
   frame1->set_label_align(0,0.5);
   frame1->add(*vbox1);
   frame1->set_label_widget(*label8);
   viewport->set_shadow_type(Gtk::SHADOW_NONE);
   viewport->add(*tree);
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow1->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow1->add(*viewport);
   WTelefon->attach(*button2, 0, 1, 2, 3, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   WTelefon->attach(*frame1, 0, 1, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::FILL, 0, 0);
   WTelefon->attach(*scrolledwindow1, 0, 1, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   button2->show();
   option_menu->show();
   vbox_telnr->show();
   _land->show();
   label9->show();
   frame2->show();
   _vorwahl->show();
   label10->show();
   frame3->show();
   _nummer->show();
   label11->show();
   frame4->show();
   _durchwahl->show();
   label12->show();
   frame5->show();
   telnummer_box->show();
   hbox10->show();
   textfeld->show();
   label13->show();
   text_box->show();
   hbox11->show();
   vbox1->show();
   label8->show();
   frame1->show();
   tree->show();
   viewport->show();
   scrolledwindow1->show();
   WTelefon->show();
   button2->signal_clicked().connect(SigC::slot(*this, &WTelefon_glade::on_buttonNumLoeschen_clicked), false);
   option_menu->get_menu()->signal_deactivate().connect(SigC::slot(*this, &WTelefon_glade::anderer_typ), false);
   _land->signal_activate().connect(SigC::slot(*this, &WTelefon_glade::land_activate), false);
   _vorwahl->signal_activate().connect(SigC::slot(*this, &WTelefon_glade::vorwahl_activate), false);
   _nummer->signal_activate().connect(SigC::slot(*this, &WTelefon_glade::nummer_activate), false);
   _durchwahl->signal_activate().connect(SigC::slot(*this, &WTelefon_glade::durchwahl_activate), false);
   textfeld->signal_activate().connect(SigC::slot(*this, &WTelefon_glade::text_activate), false);
}

WTelefon_glade::~WTelefon_glade()
{  delete tree;
}
