#!/bin/sh
echo ./autogen.sh --includedir=`petiglibs-config --incdir Komponenten` \
	--libdir=`petiglibs-config --libdir Komponenten`
echo ---------------------------------------------------------
./autogen.sh --includedir=`petiglibs-config --incdir Komponenten` \
	--libdir=`petiglibs-config --libdir Komponenten`
