// generated 2004/5/18 11:37:42 CEST by jacek@jaceksdell.(none)
// using glademm V2.0.0.2
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jacek/cvs/manuproc/ManuProC_Agent/mpc_agent.glade
// for gtk 2.2.4 and gtkmm 2.2.8
//
// Please modify the corresponding derived classes in ./src/mpc_export.hh and./src/mpc_export.cc

#ifndef _MPC_EXPORT_GLADE_HH
#  define _MPC_EXPORT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/entry.h>

class mpc_export_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Button *export_close;
        class Gtk::Entry *export_file_name;
        
        mpc_export_glade();
        
        ~mpc_export_glade();
private:
        virtual void on_file_select_clicked() = 0;
        virtual void on_do_file_export_clicked() = 0;
        virtual void on_do_file_send_clicked() = 0;
};
#endif
