#! /bin/bash

AKTION=$1
DB=$PGDATABASE
PSFILE=lager_ungebucht


OUTFILE_L=ung_lfrs

# für Lieferscheine
INSTANZ=1

psql $DB  -o $OUTFILE_L -c " \
SELECT \
l.lfrsid as LS_NR, \
e.zeile as zeile, \
e.stueck as menge, \
l.datum as datum, \
artikelbezeichnung(e.artikelid) as artikel \
from lieferschein l join lieferscheinentry e on \
((l.lfrsid,l.instanz)=(e.lfrsid,e.instanz) and l.instanz=$INSTANZ and e.status=0 \
 and coalesce(e.lagerid,1)!=0) left join \
rechnung r on (r.rngid=l.rngid) \
where coalesce(r.rngart,'R')='R' order by l.lfrsid,e.zeile"


# für Wareneingang
INSTANZ=3
OUTFILE_W=ung_wrei

psql $DB  -o $OUTFILE_W -c " \
SELECT \
l.lfrsid as LS_NR, \
e.zeile as zeile, \
e.stueck as menge, \
l.datum as datum, \
artikelbezeichnung(e.artikelid) as artikel \
from lieferschein l join lieferscheinentry e on \
((l.lfrsid,l.instanz)=(e.lfrsid,e.instanz) and l.instanz=$INSTANZ and e.status=0 \
 and coalesce(e.lagerid,1)!=0) left join \
rechnung r on (r.rngid=l.rngid) \
where coalesce(r.rngart,'R')='R' order by l.lfrsid,e.zeile"


echo "   Lieferscheine   " > $PSFILE
cat $OUTFILE_L >> $PSFILE
echo "" >> $PSFILE
echo "   Wareneingang   " >> $PSFILE
cat $OUTFILE_W >> $PSFILE



a2ps -R --center-title="ungebuchte Lieferscheine / Wareneingang" \
--columns 1 $PSFILE -o $PSFILE.ps

if [ "$AKTION" == "P" ]; then
	if [ ! "$MANUPROC_PR_TRAY1" ]; then
		lpr $PSFILE.ps
	else
		lpr -P $MANUPROC_PR_TRAY1 $PSFILE.ps
	fi
elif [ "$AKTION" == "V" ]; then
	gs -dBATCH $PSFILE.ps
fi


