// generated 2004/11/16 12:42:47 CET by christof@felix.petig.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- marc.glade
// for gtk 2.4.13 and gtkmm 2.4.5
//
// Please modify the corresponding derived classes in ././window2.hh and././window2.cc

#ifndef _WINDOW2_GLADE_HH
#  define _WINDOW2_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>

class window2_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        
        window2_glade();
        
        ~window2_glade();
private:
        virtual void on_item1_activate() = 0;
        virtual void on_item3_activate() = 0;
        virtual void on_item4_activate() = 0;
};
#endif
