/*  libKomponenten: GUI components for ManuProC's libcommon++
 *  Copyright (C) 2001 Adolf Petig GmbH & Co. KG, written by Jacek Jakubowski
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/3/14 12:16:07 CET by christof@puck.(none)
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- marc.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./marc2/window1.hh and./marc2/window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH

#include <gtk--/window.h>
#include "Datewin.hh"
#include "ProzessBox.hh"
#include "ArtikelBox.hh"
#include "KundenBox.hh"
#include <gtk--/box.h>

class window1_glade : public Gtk::Window
{   
protected:
        
        class Datewin *datum;
        class ProzessBox *prozess;
        class ArtikelBox *artikelbox;
        class KundenBox *kundenbox;
        class Gtk::VBox *vbox1;
        
        window1_glade();
        
        ~window1_glade();
};
#endif
