// generated 2001/10/11 11:47:12 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/common/Komponenten/examples/artikelbox/marc.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ././window1.hh and././window1.cc

#ifndef _WINDOW1_GLADE_HH
#  define _WINDOW1_GLADE_HH

#include <gtk--/window.h>
#include "WPreis.hh"
#include "WAuftragStatus.hh"
#include "WWaehrung.hh"
#include "Datewin.hh"
#include "ProzessBox.hh"
#include "ArtikelBox.hh"
#include "KundenBox.hh"
#include <gtk--/box.h>

class window1_glade : public Gtk::Window
{   
protected:
        
        class WPreis *WPreis;
        class WAuftragStatus *WAufStat;
        class WWaehrung *WWaehrung;
        class Datewin *datum;
        class ProzessBox *prozess;
        class ArtikelBox *artikelbox;
        class ArtikelBox *artikelbox2;
        class KundenBox *kundenbox;
        class Gtk::VBox *vbox1;
        
        window1_glade();
        
        ~window1_glade();
};
#endif
