// generated 2001/8/14 14:08:49 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/common/Komponenten/examples/artikelbox/marc.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ././window1.cc

#include "config.h"
#include "window1.hh"
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/button.h>
#include <gtk--/label.h>

window1_glade::window1_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *window1 = this;
   Gtk::MenuItem *Beenden = NULL;
   Gtk::Menu *menu1 = manage(new class Gtk::Menu());
   Gtk::MenuItem *Datei = NULL;
   Gtk::MenuBar *menubar1 = manage(new class Gtk::MenuBar());
   WPreis = new class WPreis();
   
   Gtk::Button *button1 = manage(new class Gtk::Button("Show contents"));
   WAufStat = new class WAuftragStatus();
   WWaehrung = new class WWaehrung(WWaehrung::LANG);
   
   Gtk::Label *label1 = manage(new class Gtk::Label("Some label to demonstrate pack_end"));
   datum = new class Datewin();
   prozess = new class ProzessBox();
   artikelbox = new class ArtikelBox(cH_ExtBezSchema(1,ArtikelTyp::GewebtesBand));
   kundenbox = new class KundenBox();
   
   Gtk::Button *button2 = manage(new class Gtk::Button("reset"));
   vbox1 = manage(new class Gtk::VBox(false, 0));
   
   
   menu1->items().push_back(Gtk::Menu_Helpers::MenuElem("Beenden"));
   Beenden = (Gtk::MenuItem *)menu1->items().back();
   
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("Datei", *menu1));
   Datei = (Gtk::MenuItem *)menubar1->items().back();
   WPreis->set_usize(50, 27);
   WAufStat->set_usize(-1, 25);
   WWaehrung->set_usize(-1, 29);
   label1->set_alignment(0.5, 0.5);
   label1->set_padding(0, 0);
   datum->set_usize(-1, 20);
   prozess->set_usize(-1, 20);
   artikelbox->set_usize(-1, 50);
   kundenbox->set_usize(-1, 40);
   vbox1->pack_start(*menubar1, false, true, 0);
   vbox1->pack_end(*WPreis);
   vbox1->pack_end(*button1, false, false, 0);
   vbox1->pack_end(*WAufStat);
   vbox1->pack_end(*WWaehrung);
   vbox1->pack_end(*label1, false, false, 0);
   vbox1->pack_start(*datum);
   vbox1->pack_start(*prozess);
   vbox1->pack_start(*artikelbox);
   vbox1->pack_start(*kundenbox);
   vbox1->pack_start(*button2, false, false, 0);
   window1->set_title("window1");
   window1->set_policy(true, true, false);
   window1->add(*vbox1);
   Beenden->show();
   menu1->show();
   Datei->show();
   menubar1->show();
   WPreis->show();
   button1->show();
   WAufStat->show();
   WWaehrung->show();
   label1->show();
   datum->show();
   prozess->show();
   artikelbox->show();
   kundenbox->show();
   button2->show();
   vbox1->show();
   window1->show();
   Beenden->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_Beenden_activate));
   WPreis->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_activate_wpreis));
   button1->clicked.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_show_clicked));
   WWaehrung->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_activate_wwaehrung));
   datum->activate.connect(prozess->grab_focus.slot());
   prozess->activate.connect(artikelbox->grab_focus.slot());
   artikelbox->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_show_complete));
   kundenbox->activate.connect(SigC::slot(static_cast<class window1*>(this), &window1::andererKunde));
   button2->clicked.connect(SigC::slot(static_cast<class window1*>(this), &window1::on_reset));
}

window1_glade::~window1_glade()
{   delete WPreis;
   delete WAufStat;
   delete WWaehrung;
   delete datum;
   delete prozess;
   delete artikelbox;
   delete kundenbox;
}
