// $Id: window2_glade.cc,v 1.2 2002/11/22 14:28:20 christof Exp $
/*  libKomponenten: ManuProC's Widget library
 *  Copyright (C) 2002 Adolf Petig GmbH & Co. KG
 *  written by Jacek Jakubowski, Christof Petig, Malte Thoma
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2002/5/16 16:24:34 CEST by christof@puck.petig-baender.de
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- marc.glade
// for gtk 2.0.2 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ././window2.cc

#include "config.h"
#include "window2.hh"
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/table.h>

window2_glade::window2_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *window2 = this;
   Gtk::MenuItem *item1 = NULL;
   Gtk::MenuItem *item3 = NULL;
   Gtk::MenuItem *item4 = NULL;
   Gtk::Menu *item2_menu = manage(new class Gtk::Menu());
   Gtk::MenuItem *item2 = NULL;
   Gtk::MenuItem *trennlinie1 = NULL;
   Gtk::MenuBar *menubar2 = manage(new class Gtk::MenuBar());
   Gtk::Table *table1 = manage(new class Gtk::Table(3, 3, false));
   
   item2_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("text3"));
   item3 = (Gtk::MenuItem *)item2_menu->items().back();
   
   item2_menu->items().push_back(Gtk::Menu_Helpers::MenuElem("text4"));
   item4 = (Gtk::MenuItem *)item2_menu->items().back();
   
   menubar2->items().push_back(Gtk::Menu_Helpers::MenuElem("text1"));
   item1 = (Gtk::MenuItem *)menubar2->items().back();
   
   menubar2->items().push_back(Gtk::Menu_Helpers::MenuElem("text2", *item2_menu));
   item2 = (Gtk::MenuItem *)menubar2->items().back();
   
   menubar2->items().push_back(Gtk::Menu_Helpers::SeparatorElem());
   trennlinie1 = (Gtk::MenuItem *)menubar2->items().back();
   table1->attach(*menubar2, 0, 1, 0, 1, GTK_FILL, 0, 0, 0);
   window2->set_title("window2");
   window2->add(*table1);
   item1->show();
   item3->show();
   item4->show();
   item2_menu->show();
   item2->show();
   trennlinie1->show();
   menubar2->show();
   table1->show();
   window2->show();
   item1->activate.connect(SigC::slot(static_cast<class window2*>(this), &window2::on_item1_activate));
   item3->activate.connect(SigC::slot(static_cast<class window2*>(this), &window2::on_item3_activate));
   item4->activate.connect(SigC::slot(static_cast<class window2*>(this), &window2::on_item4_activate));
}

window2_glade::~window2_glade()
{  
}
