#!/bin/bash

export PGHOST=localhost
export PGDATABASE=mabella_testdb
P="database_tables_init_Mabella"

dropdb $PGDATABASE
createdb -E SQL_ASCII $PGDATABASE

(for i in \
   waehrung \
   lkz_sprache \
   einheiten \
   fw_lager_buchung \
   prozesse \
   prod_instanz \
   ku_briefanr \
   ku_land \
   kunden \
   ku_verkaeufer \
   rechnung_zahlungsart \
   artikelbezeichnung \
   artikelstamm \
   artikelzusammensetzung \
   artbez_3_23001 \
   artbez_3_1 \
   artbez_12_1 \
   artbez_warengruppe \
   auftrag \
   auftragentry \
   auftrag_prozess \
   auftragsentryzuordnung \
   banken \
   extbezschema \
   global_settings \
   rechnung \
   rechnungentry \
   artikelpreise \
   lieferschein \
   lieferscheinentry \
   lieferscheinentryzusatz \
   problems \
   prod_changejournal \
   prod_changejournal_chid_seq \
   ueberweisungen \
   prov_abrechnung \
   prov_verkaeufer \
   prov_config \
   artbez_insert \
   artikel_bestand \
   artikelgruppen \
   ku_gruppe \
   lager
do
  cat $P/$i
done ) | psql $PGDATABSE -q

../../Programme/db_upgrade
../../Programme/Instanzen $PGDATABASE

psql $PGDATABASE -c "vacuum analyze"

