// generated 2005/6/24 11:37:58 CEST by christof@vesta.petig-baender.de
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- kundendaten.glade
// for gtk 2.7.0 and gtkmm 2.6.3
//
// Please modify the corresponding derived classes in ./src/dialogError.hh and./src/dialogError.cc

#ifndef _DIALOGERROR_GLADE_HH
#  define _DIALOGERROR_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>

class dialogError_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Dialog * dialogError;
        
        dialogError_glade();
        
        ~dialogError_glade();
};
#endif
