// generated 2005/6/27 17:51:58 CEST by christof@vesta.petig-baender.de
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- kundendaten.glade
// for gtk 2.7.0 and gtkmm 2.6.3
//
// Please modify the corresponding derived classes in ./src/dialogBestaetigen.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dialogBestaetigen_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/eventbox.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>

dialogBestaetigen_glade::dialogBestaetigen_glade(
)
{  dialogBestaetigen = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *button2 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::Button *button4 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::EventBox *eventbox3 = Gtk::manage(new class Gtk::EventBox());
   Gtk::Label *label7 = Gtk::manage(new class Gtk::Label("Kundennr"));
   neuekdnr = Gtk::manage(new class Gtk::Entry());
   
   Gtk::HBox *hbox6 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::VBox *vbox2 = Gtk::manage(new class Gtk::VBox(false, 0));
   button2->set_flags(Gtk::CAN_FOCUS);
   button2->set_flags(Gtk::CAN_DEFAULT);
   button2->set_relief(Gtk::RELIEF_NORMAL);
   button4->set_flags(Gtk::CAN_FOCUS);
   button4->set_flags(Gtk::CAN_DEFAULT);
   button4->set_relief(Gtk::RELIEF_NORMAL);
   dialogBestaetigen->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_SPREAD);
   label7->set_alignment(0,0.5);
   label7->set_padding(0,0);
   label7->set_justify(Gtk::JUSTIFY_CENTER);
   label7->set_line_wrap(false);
   label7->set_use_markup(false);
   label7->set_selectable(false);
   neuekdnr->set_flags(Gtk::CAN_FOCUS);
   neuekdnr->set_visibility(true);
   neuekdnr->set_editable(true);
   neuekdnr->set_max_length(0);
   neuekdnr->set_text("");
   neuekdnr->set_has_frame(true);
   neuekdnr->set_activates_default(false);
   hbox6->pack_start(*label7);
   hbox6->pack_start(*neuekdnr);
   vbox2->pack_start(*eventbox3);
   vbox2->pack_start(*hbox6, Gtk::PACK_SHRINK, 0);
   dialogBestaetigen->get_vbox()->set_homogeneous(false);
   dialogBestaetigen->get_vbox()->set_spacing(8);
   dialogBestaetigen->get_vbox()->pack_start(*vbox2);
   dialogBestaetigen->set_title("Vergabe der Kundennummer");
   dialogBestaetigen->set_modal(true);
   dialogBestaetigen->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dialogBestaetigen->set_resizable(true);
   dialogBestaetigen->property_destroy_with_parent().set_value(false);
   dialogBestaetigen->set_has_separator(true);
   dialogBestaetigen->add_action_widget(*button2, -5);
   dialogBestaetigen->add_action_widget(*button4, -6);
   button2->show();
   button4->show();
   eventbox3->show();
   label7->show();
   neuekdnr->show();
   hbox6->show();
   vbox2->show();
   dialogBestaetigen->show();
}

dialogBestaetigen_glade::~dialogBestaetigen_glade()
{  delete gmm_data;
}
