// generated 2002/3/25 15:42:25 CET by thoma@Tiger.(none)
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/christof/kundendaten/kundendaten.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/dialogInfo.hh and./src/dialogInfo.cc

#ifndef _DIALOGINFO_GLADE_HH
#  define _DIALOGINFO_GLADE_HH

#include <gnome--/messagebox.h>

class dialogInfo_glade : public Gnome::MessageBox
{  
protected:
        
        class Gnome::MessageBox *dialogInfo;
        
        dialogInfo_glade();
        
        ~dialogInfo_glade();
};
#endif
