// generated 2002/9/24 12:19:12 CEST by thoma@Tiger.(none)
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- kundendaten.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/dialogError.cc

#include "config.h"
#include "dialogError.hh"
#include <vector>
#include <libgnomeui/gnome-stock.h>
#include <gtk--/button.h>
#include <gtk--/buttonbox.h>
#include <gtk--/box.h>

dialogError_glade::dialogError_glade(
)
{  dialogError = this;
   dialogError->append_button(GNOME_STOCK_BUTTON_OK);
   dialogError->get_button(0)->set_flags(GTK_CAN_FOCUS);
   dialogError->get_vbox()->set_homogeneous(false);
   dialogError->get_vbox()->set_spacing(8);
   dialogError->set_title("Information");
   dialogError->set_modal(true);
   dialogError->set_position(GTK_WIN_POS_CENTER);
   dialogError->set_policy(false, false, false);
   
   Gtk::HButtonBox *dialog_action_area3 = Gtk::wrap((GtkHButtonBox*)GNOME_DIALOG(dialogError->gtkobj())->action_area);
   dialog_action_area3->set_spacing(8);
   dialogError->close_hides(false);
   dialogError->show();
}

dialogError_glade::~dialogError_glade()
{  
}
