// generated 2005/6/24 11:37:58 CEST by christof@vesta.petig-baender.de
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- kundendaten.glade
// for gtk 2.7.0 and gtkmm 2.6.3
//
// Please modify the corresponding derived classes in ./src/window_Dialog_Bestaetigen.hh and./src/window_Dialog_Bestaetigen.cc

#ifndef _WINDOW_DIALOG_BESTAETIGEN_GLADE_HH
#  define _WINDOW_DIALOG_BESTAETIGEN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>

class window_Dialog_Bestaetigen_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Window * window_Dialog_Bestaetigen;
        class Gtk::Label * label_text;
        
        window_Dialog_Bestaetigen_glade();
        
        ~window_Dialog_Bestaetigen_glade();
private:
        virtual void on_button_ok_clicked() = 0;
        virtual void on_button_cancel_clicked() = 0;
};
#endif
