// generated 2003/4/12 13:40:55 MEST by jacek@ijacek.jacek.de
// using glademm V1.1.3f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jacek/cvs/kundendaten/kundendaten.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/window_neue_Kundennummer.hh and./src/window_neue_Kundennummer.cc

#ifndef _WINDOW_NEUE_KUNDENNUMMER_GLADE_HH
#  define _WINDOW_NEUE_KUNDENNUMMER_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/entry.h>
#include "Optionmenu_Kundengruppe.hh"
#include <gtk--/frame.h>
#include <gtk--/button.h>

class window_neue_Kundennummer_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Entry *entry_firma;
        class Gtk::Entry *entry_kundennr;
        class Gtk::Entry *entry_name2;
        class Optionmenu_Kundengruppe *custom3;
        class Gtk::Frame *gruppe;
        class Gtk::Button *button_ok;
        
        window_neue_Kundennummer_glade();
        
        ~window_neue_Kundennummer_glade();
private:
        virtual void on_firma_activate() = 0;
        virtual void on_kundennr_activate() = 0;
        virtual void on_name2_activate() = 0;
        virtual void on_gruppenwahl_activate() = 0;
        virtual void on_button_ok_clicked() = 0;
        virtual void on_button_abbrechen_clicked() = 0;
};
#endif
