// generated 2002/9/24 12:19:12 CEST by thoma@Tiger.(none)
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- kundendaten.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/window_neue_Kundennummer.hh and./src/window_neue_Kundennummer.cc

#ifndef _WINDOW_NEUE_KUNDENNUMMER_GLADE_HH
#  define _WINDOW_NEUE_KUNDENNUMMER_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/entry.h>

class window_neue_Kundennummer_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Entry *entry_kundennr;
        class Gtk::Entry *entry_firma;
        
        window_neue_Kundennummer_glade();
        
        ~window_neue_Kundennummer_glade();
};
#endif
