#!/bin/sh

psql $1 <<EOF
delete from artikelzusammensetzung;
delete from prod_changejournal;
delete from auftrag_prozess;
delete from auftragsentryzuordnung;
delete from auftragentry;
delete from auftrag;
delete from lieferscheinentry;
delete from lieferschein;
vacuum analyze;
EOF
../../Programme/Instanzen $1
