#!/bin/sh

if [ $1empty = "empty" ]; then exit 1; fi

psql $1 <<EOF
delete from prod_changejournal;
delete from auftrag_prozess;
delete from auftragsentryzuordnung;
delete from auftragentry;
delete from auftrag;
delete from lieferscheinentry;
delete from lieferschein;
delete from rechnung_zahlungsart where kurzbezeichnung='test';
vacuum analyze;
EOF
../../Programme/Instanzen $1
