#!/bin/bash
# 1. Argument: Test mit dem begonnen werden soll

TABLES=`./where_are_the_tables`
case $TABLES in
   */Anleitung/datenbank)
   	ALLTESTS="MP AP ZK"
   	;;
   database_tables_init)
   	ALLTESTS="M P S L Z D Ls Lm LZ LA ZK ZKM J ZI ZI2 AL Pt V V2 V3 RP Rg RK RZ RKZ"
   	;;
   database_tables_init_Mabella)
   	BROKEN="ZK"
   	ALLTESTS="fun LSR AM roll minMen minMenRep minMen_LS minMenR2 ZuA DAeA DAeA_Tl DAeE2 SplE ZuA LBR LBL AOL"
   	;;
   *) echo "Kann $TABLES nicht identifizieren"
   	exit 2
   	;;
esac

if [ $# -lt 1 ]
then TESTS="$ALLTESTS"
else
  copy=0
  for a in $ALLTESTS
  do
    if [ $copy -gt 0 ]
    then TESTS="$TESTS $a"
    else
      if [ $a = "$1" ]
      then 
        copy=1
        TESTS=$a
      fi
    fi
  done
  if [ $copy -gt 0 ] 
  then shift
  else TESTS="$ALLTESTS"
  fi
fi

for x in $TESTS ; do
  if ./steuerprogramm -C $* $x
  then
    echo ./steuerprogramm $x OK ;
  else
    echo Abbruch bei $x
    exit;
  fi
done
