#!/bin/bash
# 1. Argument: Test mit dem begonnen werden soll

case `./where_are_the_tables` in
   */Anleitung/datenbank)
   	ALLTESTS="MP AL ZK"
   	;;
   petigdb)
   	ALLTESTS="M P S L Z D Ls Lm LZ LA ZK ZKM J ZI ZI2 AL RP Rg RK RZ RKZ"
   	;;
   mabelladb)
   	ALLTESTS="LJ ZK RM"
   	;;
   *) ALLTESTS=""
   	;;
esac

if [ $# -lt 1 ]
then TESTS="$ALLTESTS"
else
  copy=0
  for a in $ALLTESTS
  do
    if [ $copy -gt 0 ]
    then TESTS="$TESTS $a"
    else
      if [ $a = "$1" ]
      then 
        copy=1
        TESTS=$a
      fi
    fi
  done
  if [ $copy -gt 0 ] 
  then shift
  else TESTS="$ALLTESTS"
  fi
fi

for x in $TESTS ; do
  if ./steuerprogramm -C $* $x
  then
    echo ./steuerprogramm $x OK ;
  else
    echo Abbruch bei $x
    exit;
  fi
done
