#!/bin/sh
DBLINE=`fgrep DEFAULT_DB ../../ManuProCConfig.h`
DB=`echo $DBLINE | ( read a b c d ; echo $c )`
DB2=`echo $DB | sed -e 's/"//g' `

case $DB2 in
	anleitungdb)
		echo ../../../Anleitung/datenbank 
		;;
	petigdb)
		echo database_tables_init
		;;
	mabelladb)
		echo database_tables_init_Mabella
		;;
	*)
		echo >&2 Unknown default database $DB2.
		exit 1
		;;
esac
