#!/bin/bash

dot -Tps << END > G.ps 
digraph G {
		size="10.5,7.9";
		ratio=fill;
		rotate=90;
		center=true;

	node [shape=record];
		filenames [label="{mit_lager_open | ZK_anlegen | ZK_abschreiben1T | ZK_abschreiben2T}|{ |  |  | }"];


	subgraph p_1 {
		node [shape=record];
		my_1 [label="{Kundenaufträge/20000/1 | (31.12.2010,1)/// | 400//400(300)/}"];
		fontsize=8;}

	subgraph p_2 {
		node [shape=record];
		my_2 [label="{Kundenaufträge/20001/1 | (31.12.2020,1)// | 200//200(180)}"];
		fontsize=8;}

	subgraph p_3 {
		node [shape=Mrecord];
		my_3 [label="{Rollerei/0/1 | (31.12.2010,1)/// | 400//100/0}"];
		fontsize=8;}

	subgraph p_4 {
		node [shape=Mrecord];
		my_4 [label="{Rollerei/0/2 | (31.12.2020,1)// | 200//120}"];
		fontsize=8;}

	subgraph p_5 {
		node [shape=record];
		my_5 [label="{Rollerei/1/1 | (31.12.2010,2)/ | 300(300)/}"];
		fontsize=8;}

	subgraph p_6 {
		node [shape=record];
		my_6 [label="{Rollerei/1/2 | (31.12.2010,2) | 100(100)}"];
		fontsize=8;}

	subgraph p_7 {
		node [shape=record];
		my_7 [label="{Rollerei/1/3 | (31.12.2020,2) | 80(80)}"];
		fontsize=8;}

	subgraph p_8 {
		node [shape=Mrecord];
		my_8 [label="{Färberei/0/1 | (29.12.2010,1)/// | 10000//2500/0}"];
		fontsize=8;}

	subgraph p_9 {
		node [shape=Mrecord];
		my_9 [label="{Färberei/0/2 | (29.12.2020,1)// | 5000//3000}"];
		fontsize=8;}

	subgraph p_10 {
		node [shape=record];
		my_10 [label="{Färberei/1/1 | (29.12.2010,2)/ | 7500(7500)/}"];
		fontsize=8;}

	subgraph p_11 {
		node [shape=record];
		my_11 [label="{Färberei/1/2 | (29.12.2010,2) | 2500(2500)}"];
		fontsize=8;}

	subgraph p_12 {
		node [shape=record];
		my_12 [label="{Färberei/1/3 | (29.12.2020,2) | 2000(2000)}"];
		fontsize=8;}

	subgraph p_13 {
		node [shape=Mrecord];
		my_13 [label="{Bandlager/0/1 | (27.12.2010,1)/// | 8000///}"];
		fontsize=8;}

	subgraph p_14 {
		node [shape=Mrecord];
		my_14 [label="{Bandlager/0/2 | (27.12.2020,1)// | 5000//}"];
		fontsize=8;}

	subgraph p_15 {
		node [shape=record];
		my_15 [label="{Bandlager/1/1 | (27.12.2010,1)/// | 2000///}"];
		fontsize=8;}

	subgraph p_16 {
		node [shape=Mrecord];
		my_16 [label="{Bandlager/2/1 | (1.1.1970,1)/// | 0///}"];
		fontsize=8;}

	subgraph p_17 {
		node [shape=Mrecord];
		my_17 [label="{Weberei/0/1 | (27.12.2010,1)/// | 8000///}"];
		fontsize=8;}

	subgraph p_18 {
		node [shape=Mrecord];
		my_18 [label="{Weberei/0/2 | (27.12.2020,1)// | 5000//}"];
		fontsize=8;}

	subgraph p_19 {
		node [shape=Mrecord];
		my_19 [label="{Rohwarenlager/0/1 | (29.11.2010,1)/// | 58///}"];
		fontsize=8;}

	subgraph p_20 {
		node [shape=Mrecord];
		my_20 [label="{Rohwarenlager/0/2 | (29.11.2010,1)/// | 24///}"];
		fontsize=8;}

	subgraph p_21 {
		node [shape=Mrecord];
		my_21 [label="{Rohwarenlager/0/3 | (29.11.2020,1)// | 50//}"];
		fontsize=8;}

	subgraph p_22 {
		node [shape=Mrecord];
		my_22 [label="{Rohwarenlager/0/4 | (29.11.2020,1)// | 30//}"];
		fontsize=8;}

	subgraph p_23 {
		node [shape=record];
		my_23 [label="{Rohwarenlager/1/1 | (29.11.2010,1)/// | 22///}"];
		fontsize=8;}

	subgraph p_24 {
		node [shape=record];
		my_24 [label="{Rohwarenlager/1/2 | (29.11.2010,1)/// | 24///}"];
		fontsize=8;}

	subgraph p_25 {
		node [shape=Mrecord];
		my_25 [label="{Rohwarenlager/2/1 | (1.1.1970,1)/// | 0///}"];
		fontsize=8;}

	subgraph p_26 {
		node [shape=Mrecord];
		my_26 [label="{Rohwarenlager/2/2 | (1.1.1970,1)/// | 0///}"];
		fontsize=8;}

	subgraph p_27 {
		node [shape=Mrecord];
		my_27 [label="{(Garn-)Einkauf/0/1 | (29.11.2010,1)/// | 58///}"];
		fontsize=8;}

	subgraph p_28 {
		node [shape=Mrecord];
		my_28 [label="{(Garn-)Einkauf/0/2 | (29.11.2010,1)/// | 24///}"];
		fontsize=8;}

	subgraph p_29 {
		node [shape=Mrecord];
		my_29 [label="{(Garn-)Einkauf/0/3 | (29.11.2020,1)// | 50//}"];
		fontsize=8;}

	subgraph p_30 {
		node [shape=Mrecord];
		my_30 [label="{(Garn-)Einkauf/0/4 | (29.11.2020,1)// | 30//}"];
		fontsize=8;}

	subgraph p_31 {
		node [shape=Mrecord];
		my_31 [label="{Spritzgießerei/0/1 | (29.12.2010,1)/// | 800//200/0}"];
		fontsize=8;}

	subgraph p_32 {
		node [shape=Mrecord];
		my_32 [label="{Spritzgießerei/0/2 | (29.12.2020,1)// | 400//240}"];
		fontsize=8;}

	subgraph p_33 {
		node [shape=record];
		my_33 [label="{Spritzgießerei/1/1 | (29.12.2010,2)/ | 600(600)/}"];
		fontsize=8;}

	subgraph p_34 {
		node [shape=record];
		my_34 [label="{Spritzgießerei/1/2 | (29.12.2010,2) | 200(200)}"];
		fontsize=8;}

	subgraph p_35 {
		node [shape=record];
		my_35 [label="{Spritzgießerei/1/3 | (29.12.2020,2) | 160(160)}"];
		fontsize=8;}

	my_1 -> my_3 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="400///"];

	my_2 -> my_4 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="200//"];

	my_3 -> my_5 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="300/", weight=-1];
	{rank=same;my_3 my_5}

	my_3 -> my_6 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="100", weight=-1];
	{rank=same;my_3 my_6}

	my_3 -> my_8 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="10000///"];

	my_3 -> my_31 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="800///"];

	my_4 -> my_7 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="80", weight=-1];
	{rank=same;my_4 my_7}

	my_4 -> my_9 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="5000//"];

	my_4 -> my_32 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="400//"];

	my_8 -> my_10 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="7500/", weight=-1];
	{rank=same;my_8 my_10}

	my_8 -> my_11 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="2500", weight=-1];
	{rank=same;my_8 my_11}

	my_8 -> my_13 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="10000///"];

	my_9 -> my_12 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="2000", weight=-1];
	{rank=same;my_9 my_12}

	my_9 -> my_14 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="5000//"];

	my_13 -> my_15 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="2000///", weight=-1];
	{rank=same;my_13 my_15}

	my_13 -> my_17 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="8000///"];

	my_14 -> my_18 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="5000//"];

	my_17 -> my_19 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="80///"];

	my_17 -> my_20 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="48///"];

	my_18 -> my_21 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="50//"];

	my_18 -> my_22 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="30//"];

	my_19 -> my_23 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="22///", weight=-1];
	{rank=same;my_19 my_23}

	my_19 -> my_27 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="58///"];

	my_20 -> my_24 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="24///", weight=-1];
	{rank=same;my_20 my_24}

	my_20 -> my_28 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="24///"];

	my_21 -> my_29 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="50//"];

	my_22 -> my_30 [fontsize=10,labeldistance=2,labelangle=0, labelfontsize=12,labelfontcolor=black,headlabel="30//"];

	my_31 -> my_33 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="600/", weight=-1];
	{rank=same;my_31 my_33}

	my_31 -> my_34 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="200", weight=-1];
	{rank=same;my_31 my_34}

	my_32 -> my_35 [fontsize=10,labeldistance=3.5,labelangle=90, labelfontsize=12,labelfontcolor=black,headlabel="160", weight=-1];
	{rank=same;my_32 my_35}
		label="ZweiKunden"
		labelloc=top
}
END

gv G.ps &

