#!/bin/bash

dot -Tps << END > G.ps 
digraph G {
		size="10.5,7.9";
		ratio=fill;
		rotate=90;
		center=true;

	node [shape=record];
		filenames [label="{mit_lager_open | rep_pf | rep_zwei_auftraege_anlegen}|{ |  | }"];


	subgraph p_1 {
		node [shape=record];
		my_1 [label="{Kundenaufträge/20000/1 | 1271.35.760.25 | (31.12.2010,1)// | 400//}"];
		fontsize=12;}

	subgraph p_2 {
		node [shape=record];
		my_2 [label="{Kundenaufträge/20001/1 | 1271.35.760.25 | (31.12.2010,1) | 300}"];
		fontsize=12;}

	subgraph p_3 {
		node [shape=Mrecord];
		my_3 [label="{Rollerei/0/1 | 1271.35.760.25 | (31.12.2010,1)// | 400//700}"];
		fontsize=12;}

	subgraph p_4 {
		node [shape=Mrecord];
		my_4 [label="{Färberei/0/1 | 1550/60/665 | (29.12.2010,1)// | 10000/0/500}"];
		fontsize=12;}

	subgraph p_5 {
		node [shape=Mrecord];
		my_5 [label="{Färberei/2/1 | 1550/60/665 | (29.12.2010,1)/ | 7000/0}"];
		fontsize=12;}

	subgraph p_6 {
		node [shape=record];
		my_6 [label="{Färberei/20000/1 | 1550/60/665 | (29.12.2010,1)/ | 17000/}"];
		fontsize=12;}

	subgraph p_7 {
		node [shape=Mrecord];
		my_7 [label="{Bandlager/0/1 | 1271/35/760 | (27.12.2010,1)// | 8000/15000/15500}"];
		fontsize=12;}

	subgraph p_8 {
		node [shape=record];
		my_8 [label="{Bandlager/1/1 | 1271/35/760 | (27.12.2010,1)// | 2000//}"];
		fontsize=12;}

	subgraph p_9 {
		node [shape=Mrecord];
		my_9 [label="{Bandlager/2/1 | 1271/35/760 | (1.1.1970,1)// | 0//}"];
		fontsize=12;}

	subgraph p_10 {
		node [shape=Mrecord];
		my_10 [label="{Weberei/0/1 | 1271/35/760 | (27.12.2010,1)// | 8000/15000/15500}"];
		fontsize=12;}

	subgraph p_11 {
		node [shape=Mrecord];
		my_11 [label="{Rohwarenlager/0/1 | Kupferdraht 0,10mm   daVinci | (29.11.2010,1)// | 58/128/133}"];
		fontsize=12;}

	subgraph p_12 {
		node [shape=Mrecord];
		my_12 [label="{Rohwarenlager/0/2 | Acetat 133dTex arnica  daVinci | (29.11.2010,1)// | 24/66/69}"];
		fontsize=12;}

	subgraph p_13 {
		node [shape=record];
		my_13 [label="{Rohwarenlager/1/1 | Kupferdraht 0,10mm   daVinci | (29.11.2010,1)// | 22//}"];
		fontsize=12;}

	subgraph p_14 {
		node [shape=record];
		my_14 [label="{Rohwarenlager/1/2 | Acetat 133dTex arnica  daVinci | (29.11.2010,1)// | 24//}"];
		fontsize=12;}

	subgraph p_15 {
		node [shape=Mrecord];
		my_15 [label="{Rohwarenlager/2/1 | Kupferdraht 0,10mm   daVinci | (1.1.1970,1)// | 0//}"];
		fontsize=12;}

	subgraph p_16 {
		node [shape=Mrecord];
		my_16 [label="{Rohwarenlager/2/2 | Acetat 133dTex arnica  daVinci | (1.1.1970,1)// | 0//}"];
		fontsize=12;}

	subgraph p_17 {
		node [shape=Mrecord];
		my_17 [label="{(Garn-)Einkauf/0/1 | Kupferdraht 0,10mm   daVinci | (29.11.2010,1)// | 58/128/133}"];
		fontsize=12;}

	subgraph p_18 {
		node [shape=Mrecord];
		my_18 [label="{(Garn-)Einkauf/0/2 | Acetat 133dTex arnica  daVinci | (29.11.2010,1)// | 24/66/69}"];
		fontsize=12;}

	subgraph p_19 {
		node [shape=Mrecord];
		my_19 [label="{Spritzgießerei/0/1 | Ringe 12 mm | (29.12.2010,1)// | 800//1400}"];
		fontsize=12;}

	my_1 -> my_3 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="400//"];

	my_2 -> my_3 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="300"];

	my_3 -> my_4 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="10000//17500"];

	my_3 -> my_19 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="800//1400"];

	my_4 -> my_6 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="10000/17000"];

	my_4 -> my_7 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="10000//17500"];

	my_5 -> my_6 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="7000/0"];

	my_5 -> my_7 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="7000/0"];

	my_7 -> my_8 [fontsize=12,labeldistance=3.5,labelangle=90, labelfontsize=14,labelfontcolor=black,headlabel="2000//", weight=-1];
	{rank=same;my_7 my_8}

	my_7 -> my_10 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="8000/15000/15500"];

	my_10 -> my_11 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="80/150/155"];

	my_10 -> my_12 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="48/90/93"];

	my_11 -> my_13 [fontsize=12,labeldistance=3.5,labelangle=90, labelfontsize=14,labelfontcolor=black,headlabel="22//", weight=-1];
	{rank=same;my_11 my_13}

	my_11 -> my_17 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="58/128/133"];

	my_12 -> my_14 [fontsize=12,labeldistance=3.5,labelangle=90, labelfontsize=14,labelfontcolor=black,headlabel="24//", weight=-1];
	{rank=same;my_12 my_14}

	my_12 -> my_18 [fontsize=12,labeldistance=2,labelangle=0, labelfontsize=14,labelfontcolor=black,headlabel="24/66/69"];
		label="Rep_Petig_Zuordung"
		labelloc=top
}
END

gv G.ps &

