#!/bin/bash

dot -Tps << END > M.ps
digraph G {


   S1 [shape=ellipse,fontsize=14,label="ICE-3G" ];
   S2 [shape=ellipse,fontsize=14,label="MF2" ];
   OZ [shape=ellipse,fontsize=14,label="Ozeanlast" ];

   S1 -> SEA -> OZ;
   S2 -> SEA ;      

   L [shape=ellipse,fontsize=14,label="ICE-3G-S\nICE-3G-W" ];
   E [shape=ellipse,fontsize=14,label="Erdmodell" ];

   I [shape=egg,style=filled, fillcolor=lightgrey, fontsize=14,label="Interpretation durch\nVorwärtsrechnung"];
   SEA [shape=egg,style=filled, fillcolor=lightgrey, fontsize=14,label="Lösen der\n\"sea-level-equation\""];

   L -> I;
   E -> I;
   OZ -> I;

   L2 [shape=octagon,fontsize=14,label="Eismodell" ];
   E2 [shape=octagon,fontsize=14,label="Erdmodell" ];

   I -> L2;
   I -> E2;

   L2 -> SEA [tailport=n,headport=o];
   E2 -> SEA [tailport=n,headport=w];


}
END


gv M.ps
