// generated 2001/8/13 13:51:41 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/jacek/pps/auftrag.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/auftrag_rechnung.hh and./src/auftrag_rechnung.cc

#ifndef _AUFTRAG_RECHNUNG_GLADE_HH
#  define _AUFTRAG_RECHNUNG_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include <libgnomeui/gtkpixmapmenuitem.h>
#include <gtk--/button.h>
#include "Datewin.hh"
#include "SearchComboContent.hh"
#include "KundenBox.hh"
#include <gtk--/optionmenu.h>
#include <gtk--/spinbutton.h>
#include <gtk--/label.h>
#include "WWaehrung.hh"
#include "Rg_TCList.hh"
#include <gtk--/entry.h>
#include "OffLief_TCList.hh"
#include <gtk--/box.h>

class auftrag_rechnung_glade : public Gtk::Window
{   
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Window *auftrag_rechnung;
        class Gtk::Button *rngentry_del;
        class Datewin *rngdatum;
        class SearchComboContent<int> *rngnr;
        class KundenBox *lieferkunde;
        class Gtk::OptionMenu *rabatt_typ;
        struct rabatt_typ
        {   enum enum_t 
	   {   Rabatt, Zuschlag, 
	   };
        };
        class Gtk::SpinButton *rabatt_wert;
        class Gtk::Label *label_rechnung_ctl;
        class WWaehrung *rng_WWaehrung;
        class Rg_TCList *rechnung_liste;
        class Gtk::Entry *lieferscheinnr;
        class Gtk::Button *lief_uebernehmen;
        class Datewin *lieferscheindatum;
        class OffLief_TCList *offene_lieferscheine;
        class Gtk::VBox *vbox_n_b_lieferscheine;
        
        auftrag_rechnung_glade();
        
        ~auftrag_rechnung_glade();
};
#endif
