// generated 2005/9/7 14:29:08 CEST by christof@vesta.petig-baender.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 2.8.3 and gtkmm 2.7.3
//
// Please modify the corresponding derived classes in ./src/auftrag_provision.hh and./src/auftrag_provision.cc

#ifndef _AUFTRAG_PROVISION_GLADE_HH
#  define _AUFTRAG_PROVISION_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include "KundenBox2.hh"
#include <gtkmm/entry.h>
#include "datewin.hh"
#include <gtkmm/frame.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/treeview.h>

class auftrag_provision_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Dialog * auftrag_provision;
        class Gtk::Button * prov_ok;
        class KundenBox2 * prov_aufkunde;
        class Gtk::Entry * prov_aufnr;
        class datewin * prov_aufdatum;
        class Gtk::Frame * main_frame;
        class Gtk::CheckButton * prov_enable;
        class KundenBox2 * prov_verkaeufer;
        class Gtk::SpinButton * prov_provsatz;
        class Gtk::Button * prov_apply;
        class Gtk::TreeView * prov_aufentries;
        class Gtk::Frame * entry_frame;
        class Gtk::Frame * verkprov_frame;
        
        auftrag_provision_glade();
        
        ~auftrag_provision_glade();
private:
        virtual void on_prov_ok_clicked() = 0;
        virtual void on_prov_enable_toggled() = 0;
        virtual void on_prov_verk_activate() = 0;
        virtual void on_prov_provsatz_changed() = 0;
        virtual void on_prov_apply_clicked() = 0;
};
#endif
