// generated 2003/5/13 14:25:27 MEST by jacek@ijacek.jacek.de
// using glademm V1.1.3f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jacek/cvs/pps/auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/auftrag_copy.hh and./src/auftrag_copy.cc

#ifndef _AUFTRAG_COPY_GLADE_HH
#  define _AUFTRAG_COPY_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gnome--/dialog.h>
#include <gtk--/tooltips.h>
#include <gtk--/entry.h>
#include "datewin.hh"
#include "KundenBox2.hh"
#include <gtk--/spinbutton.h>
#include <gtk--/frame.h>
#include <gtk--/checkbutton.h>

class auftrag_copy_glade : public Gnome::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        Gtk::Tooltips _tooltips;
        class Gnome::Dialog *auftrag_copy;
        class Gtk::Entry *alt_aufnr;
        class datewin *alt_aufdatum;
        class KundenBox2 *alt_aufkunde;
        class KundenBox2 *neu_aufkunde;
        class datewin *neu_lieferdatum;
        class Gtk::Entry *neu_youraufnr;
        class Gtk::SpinButton *neu_stueck;
        class Gtk::Frame *frame44;
        class Gtk::CheckButton *liefdate_uebernehmen;
        class Gtk::CheckButton *stueck_uebernehmen;
        
        auftrag_copy_glade();
        
        ~auftrag_copy_glade();
private:
        virtual void on_copy_ok_clicked() = 0;
        virtual void on_copy_cancel_clicked() = 0;
};
#endif
