// generated 2001/12/17 12:04:35 CET by thoma@Tiger.
// using glademm V0.6.2b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/jacek/pps/auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/auftrag_main.hh and./src/auftrag_main.cc

#ifndef _AUFTRAG_MAIN_GLADE_HH
#  define _AUFTRAG_MAIN_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include <libgnomeui/gtkpixmapmenuitem.h>
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/radiomenuitem.h>
#include <gtk--/checkmenuitem.h>
#include <gtk--/menubar.h>
#include "SearchComboContent.hh"
#include "Datewin.hh"
#include <gtk--/spinbutton.h>
#include <gtk--/togglebutton.h>
#include "SimpleTree.hh"
#include <gtk--/label.h>
#include <gtk--/table.h>
#include <gtk--/frame.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/viewport.h>
#include <gtk--/paned.h>
#include <gtk--/button.h>

class auftrag_main_glade : public Gtk::Window
{   
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Window *auftrag_main;
        class Gtk::MenuBar *main_menubar;
        class Gtk::MenuItem *beenden;
        class Gtk::MenuItem *erfassen;
        class Gtk::MenuItem *neuladen;
        class Gtk::MenuItem *main_drucken;
        class Gtk::MenuItem *trennlinie2;
        class Gtk::MenuItem *abschreiben;
        class Gtk::RadioMenuItem *main_kndbez;
        class Gtk::RadioMenuItem *main_intbez;
        class Gtk::MenuItem *trennlinie5;
        class Gtk::RadioMenuItem *kundenauftragsnummer;
        class Gtk::RadioMenuItem *interne_auftragsnummer;
        class Gtk::MenuItem *trennlinie3;
        class Gtk::RadioMenuItem *offene_auftraege;
        class Gtk::RadioMenuItem *unbestaetigte_auftraege;
        class Gtk::RadioMenuItem *geschlossene_auftraege;
        class Gtk::RadioMenuItem *stornierte_auftraege;
        class Gtk::MenuItem *trennlinie7;
        class Gtk::RadioMenuItem *kalenderwoche;
        class Gtk::RadioMenuItem *datum;
        class Gtk::MenuItem *trennlinie4;
        class Gtk::RadioMenuItem *kunden_name1;
        class Gtk::RadioMenuItem *kunden_nr;
        class Gtk::MenuItem *trennlinie6;
        class Gtk::RadioMenuItem *materialbedarf_sortiert_nach_artikel;
        class Gtk::RadioMenuItem *materialbedarf_sortiert_nach_menge;
        class Gtk::CheckMenuItem *geplanter_materialbedarf;
        class Gtk::MenuItem *trennlinie8;
        class Gtk::RadioMenuItem *auftraege_ohne_kunde;
        class Gtk::RadioMenuItem *auftraege_mit_kunde;
        class SearchComboContent<int> *searchcombo_auftragid;
        class Datewin *Datum_instanz;
        class Gtk::SpinButton *spinbutton_geplante_menge;
        class Gtk::ToggleButton *togglebutton_geplante_menge;
        class SimpleTree *tree_neuer_auftrag;
        class Gtk::Label *info_label_instanzen;
        class Gtk::Table *table_instanzen;
        class Gtk::Frame *frame_instanzen;
        class SimpleTree *maintree_s;
        class Gtk::ScrolledWindow *scrolledwindow_maintree_s;
        class Gtk::Viewport *viewport_materialbedarf;
        class Gtk::Frame *frame_materialbedarf;
        class Gtk::VPaned *vpaned_an_mat;
        class Gtk::Button *endemain_button;
        class Gtk::Button *erfassen_button;
        class Gtk::Button *mainprint_button;
        class Gtk::Button *mainreload_button;
        class Gtk::Button *lieferschein_button;
        class Gtk::Button *rechnung_button;
        class Gtk::ToggleButton *togglebutton_material;
        class Gtk::ToggleButton *togglebutton_auftraege;
        class Gtk::Button *button_auftrag_erledigt;
        class Gtk::Button *button_Kunden_erledigt;
        
        auftrag_main_glade();
        
        ~auftrag_main_glade();
};
#endif
