// generated 2005/9/12 11:16:21 CEST by jacek@woody.mabella.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/auftrag_copy.hh and./src/auftrag_copy.cc

#ifndef _AUFTRAG_COPY_GLADE_HH
#  define _AUFTRAG_COPY_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gnome--/dialog.h>
#include <gtk--/tooltips.h>
#include <gtk--/entry.h>
#include "datewin.hh"
#include "KundenBox2.hh"
#include <gtk--/spinbutton.h>
#include <gtk--/frame.h>
#include <gtk--/checkbutton.h>

class auftrag_copy_glade : public Gnome::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        Gtk::Tooltips _tooltips;
        class Gnome::Dialog * auftrag_copy;
        class Gtk::Entry * alt_aufnr;
        class datewin * alt_aufdatum;
        class KundenBox2 * alt_aufkunde;
        class KundenBox2 * neu_aufkunde;
        class datewin * neu_lieferdatum;
        class Gtk::Entry * neu_youraufnr;
        class Gtk::SpinButton * neu_stueck;
        class Gtk::Frame * frame44;
        class Gtk::CheckButton * liefdate_uebernehmen;
        class Gtk::CheckButton * stueck_uebernehmen;
        class Gtk::CheckButton * copy_storno;
        
        auftrag_copy_glade();
        
        ~auftrag_copy_glade();
private:
        virtual void on_copy_ok_clicked() = 0;
        virtual void on_copy_cancel_clicked() = 0;
        virtual void on_liefdate_uebernehmen_toggled() = 0;
        virtual void on_stueck_uebernehmen_toggled() = 0;
};
#endif
