/*  pps: ManuProC's ProductionPlanningSystem
 *  Copyright (C) 2001 Adolf Petig GmbH & Co. KG, written by Jacek Jakubowski
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/4/19 10:29:39 CEST by christof@puck.(none)
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/auftragliste.hh and./src/auftragliste.cc

#ifndef _AUFTRAGLISTE_GLADE_HH
#  define _AUFTRAGLISTE_GLADE_HH

#include <gtk--/window.h>
#include "SearchComboContent.hh"
#include <gtk--/clist.h>
#include <gtk--/scrolledwindow.h>

class auftragliste_glade : public Gtk::Window
{   
public:
        
        class Gtk::Window *auftragliste;
        class SearchComboContent<int> *aufstatcombo;
        class Gtk::CList *selauftraglist;
        class Gtk::ScrolledWindow *scrolledwindow1;
protected:
        
        auftragliste_glade();
        
        ~auftragliste_glade();
};
#define GMM_AUFTRAGLISTE (glademm_get<auftragliste >("auftragliste"))
#define GMM_AUFSTATCOMBO (glademm_get<SearchComboContent<int> >("aufstatcombo"))
#define GMM_SELAUFTRAGLIST (glademm_get<Gtk::CList >("selauftraglist"))
#define GMM_SCROLLEDWINDOW1 (glademm_get<Gtk::ScrolledWindow >("scrolledwindow1"))
#endif
