// generated 2001/8/14 15:06:59 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/jacek/pps/auftrag.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/auftragliste.cc

#include "config.h"
#include "auftragliste.hh"
#include <gtk--/label.h>
#include <gtk--/button.h>
#include <libgnomeui/gnome-stock.h>
#include <gtk--/toolbar.h>
#include <gtk--/table.h>
#include <gtk--/viewport.h>
#include <gtk--/box.h>

auftragliste_glade::auftragliste_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   auftragliste = this;
   
   Gtk::Label *label3 = manage(new class Gtk::Label("Auftragsstatus"));
   Gtk::Toolbar *toolbar9 = manage(new class Gtk::Toolbar(GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH));
   Gtk::Button *button_erfassen = Gtk::wrap((GtkButton*)gtk_toolbar_append_element(GTK_TOOLBAR(toolbar9->gtkobj()), GTK_TOOLBAR_CHILD_BUTTON, 0, "erfassen", 0, 0, GTK_WIDGET(gnome_stock_pixmap_widget(GTK_WIDGET(toolbar9->gtkobj()), GNOME_STOCK_PIXMAP_PROPERTIES)), 0, 0));
   WAufStat = new class WAuftragStatus();
   
   Gtk::Table *table2 = manage(new class Gtk::Table(2, 3, false));
   auftragsliste = new class SimpleTree(4);
   
   Gtk::Viewport *viewport7 = manage(new class Gtk::Viewport());
   scrolledwindow1 = manage(new class Gtk::ScrolledWindow());
   
   Gtk::Button *closebutton = manage(new class Gtk::Button("Schliessen"));
   Gtk::Table *table3 = manage(new class Gtk::Table(1, 1, false));
   Gtk::VBox *vbox1 = manage(new class Gtk::VBox(false, 0));
   label3->set_alignment(0.5, 0.5);
   label3->set_padding(0, 0);
   toolbar9->set_space_size(5);
   toolbar9->set_tooltips(true);
   table2->set_border_width(5);
   table2->attach(*label3, 0, 1, 1, 2, 0, 0, 0, 0);
   table2->attach(*toolbar9, 2, 3, 1, 2, GTK_EXPAND, 0, 8, 0);
   table2->attach(*WAufStat, 1, 2, 1, 2, GTK_EXPAND|GTK_FILL, 0, 0, 0);
   viewport7->set_shadow_type(GTK_SHADOW_NONE);
   viewport7->add(*auftragsliste);
   scrolledwindow1->set_border_width(5);
   scrolledwindow1->set_policy(GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
   scrolledwindow1->add(*viewport7);
   closebutton->set_border_width(5);
   table3->attach(*closebutton, 0, 1, 0, 1, 0, 0, 0, 0);
   vbox1->pack_start(*table2, false, true, 0);
   vbox1->pack_start(*scrolledwindow1);
   vbox1->pack_start(*table3, false, true, 0);
   auftragliste->set_usize(400, 600);
   auftragliste->set_title("Auftragsauswahl");
   auftragliste->add(*vbox1);
   label3->show();
   toolbar9->show();
   WAufStat->show();
   table2->show();
   auftragsliste->show();
   viewport7->show();
   scrolledwindow1->show();
   closebutton->show();
   table3->show();
   vbox1->show();
   auftragliste->show();
   button_erfassen->clicked.connect(SigC::slot(static_cast<class auftragliste*>(this), &auftragliste::on_button_erfassen_clicked));
   WAufStat->activate.connect(SigC::slot(static_cast<class auftragliste*>(this), &auftragliste::optionmenu_stil_deactivate));
   closebutton->clicked.connect(SigC::slot(static_cast<class auftragliste*>(this), &auftragliste::on_closebutton_clicked));
}

auftragliste_glade::~auftragliste_glade()
{   delete WAufStat;
   delete auftragsliste;
}
