// generated 2001/4/26 17:26:01 CEST by christof@puck.(none)
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/auftrag_lieferschein.hh and./src/auftrag_lieferschein.cc

#ifndef _AUFTRAG_LIEFERSCHEIN_GLADE_HH
#  define _AUFTRAG_LIEFERSCHEIN_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include <libgnomeui/gtkpixmapmenuitem.h>
#include <gtk--/button.h>
#include "Datewin.hh"
#include "SearchComboContent.hh"
#include <gtk--/entry.h>
#include "KundenBox.hh"
#include "Lief_TCList.hh"
#include <gtk--/spinbutton.h>
#include "ArtikelBox.hh"
#include <gtk--/label.h>
#include "OffAuf_TCList.hh"

class auftrag_lieferschein_glade : public Gtk::Window
{   
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Window *auftrag_lieferschein;
        class Gtk::Button *lieferzeile_delete;
        class Datewin *liefdate;
        class SearchComboContent<int> *liefernr;
        class Gtk::Entry *rngnr;
        class KundenBox *liefer_kunde;
        class Lief_TCList *lieferschein_liste;
        class Gtk::SpinButton *anzahl;
        class Gtk::Entry *auftragnr;
        class ArtikelBox *artikelbox;
        class Gtk::SpinButton *Palette;
        class Gtk::SpinButton *liefermenge;
        class Gtk::Label *menge_einheit;
        class OffAuf_TCList *offene_auftraege;
        
        auftrag_lieferschein_glade();
        
        ~auftrag_lieferschein_glade();
};
#endif
