// generated 2002/9/27 16:10:54 CEST by thoma@Tiger.(none)
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/auftrag_rechnung.hh and./src/auftrag_rechnung.cc

#ifndef _AUFTRAG_RECHNUNG_GLADE_HH
#  define _AUFTRAG_RECHNUNG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include <libgnomeui/gtkpixmapmenuitem.h>
#include "WWaehrung.hh"
#include <gtk--/optionmenu.h>
#include "Datewin.hh"
#include <gtk--/spinbutton.h>
#include <gtk--/table.h>
#include "SearchComboContent.hh"
#include "KundenBox2.hh"
#include <gtk--/label.h>
#include <gtk--/frame.h>
#include <gtk--/button.h>
#include <gtk--/checkbutton.h>
#include <gtk--/radiobutton.h>
#include <gtk--/entry.h>
#include "SimpleTree.hh"
#include <gtk--/box.h>

class auftrag_rechnung_glade : public Gtk::Window
{  
        
        GlademmData *_data;
protected:
        Gtk::Tooltips _tooltips;
        class Gtk::Window *auftrag_rechnung;
        class WWaehrung *rng_WWaehrung;
        class Gtk::OptionMenu *optionmenu_zahlart;
        struct optionmenu_zahlart
        {  enum enum_t 
	   {  Zahlungsart, 
	   };
        };
        class Datewin *zahlziel;
        class Gtk::OptionMenu *rabatt_typ;
        struct rabatt_typ
        {  enum enum_t 
	   {  Rabatt, Zuschlag, 
	   };
        };
        class Gtk::SpinButton *rabatt_wert;
        class Gtk::Table *table_gutschrift_sicherheit;
        class Gtk::Table *table_gutschrift;
        class Datewin *rngdatum;
        class SearchComboContent<int> *rngnr;
        class KundenBox2 *lieferkunde;
        class Gtk::Label *label_rechnung_ctl;
        class Gtk::Frame *frame_rechnung;
        class Gtk::CheckButton *checkbutton_firmenpapier;
        class Gtk::CheckButton *checkbutton_kopie;
        class Gtk::CheckButton *checkbutton_ean_drucken;
        class Gtk::Label *label_auftragspreis;
        class Gtk::RadioButton *radiobutton_artikelpreis;
        class Gtk::RadioButton *radiobutton_auftragspreis;
        class Gtk::Label *label_artikelpreis;
        class Gtk::RadioButton *radiobutton_preiseingabe;
        class Gtk::SpinButton *spinbutton_preiseingabe;
        class Gtk::Table *table_preisvergleich;
        class Gtk::Button *button27;
        class Gtk::Button *preis_ergaenzen;
        class Gtk::Button *rngentry_del;
        class Gtk::Button *button_pr;
        class Gtk::Entry *lieferscheinnr;
        class Gtk::Button *lief_uebernehmen;
        class Datewin *lieferscheindatum;
        class Gtk::Button *button_lieferscheine_aufraumen;
        class SimpleTree *rtree_offen;
        class Gtk::VBox *vbox_n_b_lieferscheine;
        class SimpleTree *rtree_daten;
        class Gtk::Frame *frame_rechnungsdaten;
        
        auftrag_rechnung_glade();
        
        ~auftrag_rechnung_glade();
};
#endif
