// generated 2002/5/21 13:00:38 CEST by thoma@Tiger.(none)
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/jacek/pps/auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/auftrag_lieferschein.hh and./src/auftrag_lieferschein.cc

#ifndef _AUFTRAG_LIEFERSCHEIN_GLADE_HH
#  define _AUFTRAG_LIEFERSCHEIN_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include <libgnomeui/gtkpixmapmenuitem.h>
#include <gtk--/button.h>
#include "SearchComboContent.hh"
#include "Datewin.hh"
#include <gtk--/spinbutton.h>
#include <gtk--/entry.h>
#include <gtk--/table.h>
#include "KundenBox2.hh"
#include "SimpleTree.hh"
#include <gtk--/label.h>
#include "ArtikelBox.hh"
#include <gtk--/box.h>

class auftrag_lieferschein_glade : public Gtk::Window
{  
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Window *auftrag_lieferschein;
        class Gtk::Button *lieferzeile_delete;
        class SearchComboContent<int> *liefernr;
        class Datewin *liefdate;
        class Gtk::SpinButton *spinbutton_paeckchen;
        class Gtk::SpinButton *spinbutton_pakete;
        class Gtk::SpinButton *spinbutton_brutto;
        class Gtk::SpinButton *spinbutton_netto;
        class Gtk::Entry *entry_dpdnr;
        class Gtk::Table *table_mabella;
        class Gtk::Entry *rngnr;
        class KundenBox2 *liefer_kunde;
        class SimpleTree *tree_daten;
        class Gtk::SpinButton *anzahl;
        class Gtk::Label *label_kundenauftrag;
        class Gtk::Entry *auftragnr;
        class ArtikelBox *artikelbox;
        class Gtk::Button *button_zeile_uebernehmen;
        class Gtk::Button *button_kompletter_auftrag;
        class Gtk::SpinButton *Palette;
        class Gtk::SpinButton *liefermenge;
        class Gtk::Label *menge_einheit;
        class Gtk::Label *label_menge;
        class Gtk::Button *button_zeile_modifizieren;
        class SimpleTree *tree_offen;
        class Gtk::VBox *vbox_eingabe;
        
        auftrag_lieferschein_glade();
        
        ~auftrag_lieferschein_glade();
};
#endif
