// generated 2004/12/6 21:04:57 CET by jacek@jaceksdell.(none)
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jacek/cvs/pps/auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/bestell_plan.hh and./src/bestell_plan.cc

#ifndef _BESTELL_PLAN_GLADE_HH
#  define _BESTELL_PLAN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/window.h>
#include <gtk--/button.h>
#include "ArtikelBox.hh"

class bestell_plan_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Button * button42;
        class ArtikelBox * plan_artikel;
        
        bestell_plan_glade();
        
        ~bestell_plan_glade();
private:
        virtual void on_plan_artikel_activate() = 0;
};
#endif
