// generated 2006/6/23 12:46:20 CEST by jacek@jaceksdell.(none)
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jacek/Monotone/pps/auftrag.glade
// for gtk 2.8.6 and gtkmm 2.8.0
//
// Please modify the corresponding derived classes in ./src/bestell_plan.hh and./src/bestell_plan.cc

#ifndef _BESTELL_PLAN_GLADE_HH
#  define _BESTELL_PLAN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>=3
#include <gtkmm/toolbutton.h>
#else //
#include <gtkmm/button.h>
#endif //
#include "ArtikelBox.hh"
#include <gtkmm/entry.h>
#include <gtkmm/label.h>
#include <gtkmm/optionmenu.h>
#include "SimpleTree.hh"

class bestell_plan_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>=3
        class Gtk::ToolButton * bp_quit;
#else //
        class Gtk::Button * bp_quit;
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>=3
        class Gtk::ToolButton * prev_artikel;
#else //
        class Gtk::Button * prev_artikel;
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>=3
        class Gtk::ToolButton * next_artikel;
#else //
        class Gtk::Button * next_artikel;
#endif //
        class ArtikelBox * plan_artikel;
        class Gtk::Entry * bp_offauftraege;
        class Gtk::Entry * bp_verfuegbar;
        class Gtk::Entry * bp_bestellt;
        class Gtk::Entry * bp_mindbestand;
        class Gtk::Entry * bp_lagerbestand;
        class Gtk::Entry * bp_lagerbestand2;
        class Gtk::Label * lager_name2;
        class Gtk::Label * lager_name1;
        class Gtk::Entry * bp_commited;
        class Gtk::Label * commited_label;
        class Gtk::Entry * bp_uncommited;
        class Gtk::Entry * bp_rohbestellt;
        class Gtk::OptionMenu * abverkauf_kumul;
        struct abverkauf_kumul
        {  enum enum_t 
	   {  Datum, Woche, Monat, Quartal, Jahr, 
	   };
        };
        class Gtk::OptionMenu * liefdate_kumul;
        struct liefdate_kumul
        {  enum enum_t 
	   {  Datum, Woche, Monat, Quartal, Jahr, 
	   };
        };
        class Gtk::Entry * abverk_12m;
        class SimpleTree * abverkauf_tree;
        
        bestell_plan_glade();
        
        ~bestell_plan_glade();
private:
        virtual void on_bp_quit_clicked() = 0;
        virtual void on_prev_artikel_clicked() = 0;
        virtual void on_next_artikel_clicked() = 0;
        virtual void on_plan_artikel_activate() = 0;
};
#endif
