#ifdef PETIG_EXTENSIONS
#  define HIDE_PREISAUSWAHL
#  define LIEFERDATUM_WOCHE_STANDARD 1
#  define LIEFERSCHEINE_BESTAETIGT

#elif defined MABELLA_EXTENSIONS
#  define MASSENEINGABE_AUS
#  define LIEFERDATUM_WOCHE_STANDARD 1

#else
#endif
