// generated 2005/9/12 11:16:21 CEST by jacek@woody.mabella.de
// using glademm V2.10.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/ja_nein_frage.hh and./src/ja_nein_frage.cc

#ifndef _JA_NEIN_FRAGE_GLADE_HH
#  define _JA_NEIN_FRAGE_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gnome--/dialog.h>
#include <gtk--/label.h>

class ja_nein_frage_glade : public Gnome::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gnome::Dialog * ja_nein_frage;
        class Gtk::Label * label_text;
        
        ja_nein_frage_glade();
        
        ~ja_nein_frage_glade();
};
#endif
