// generated 2006/2/1 15:42:20 CET by christof@vesta.petig-baender.de
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- auftrag.glade
// for gtk 2.8.10 and gtkmm 2.8.2
//
// Please modify the corresponding derived classes in ./src/petig_we.hh and./src/petig_we.cc

#ifndef _PETIG_WE_GLADE_HH
#  define _PETIG_WE_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/entry.h>

class petig_we_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Entry * we_lfrsid;
        
        petig_we_glade();
        
        ~petig_we_glade();
private:
        virtual void on_petig_we_cancel_clicked() = 0;
        virtual void on_petig_we_ok_clicked() = 0;
};
#endif
