// generated 2002/11/4 13:51:17 CET by thoma@Tiger.(none)
// using glademm V1.1.2a_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/petig/cvs/jacek/pps/auftrag.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/termsplidial.hh and./src/termsplidial.cc

#ifndef _TERMSPLIDIAL_GLADE_HH
#  define _TERMSPLIDIAL_GLADE_HH

#include <gtk--/dialog.h>
#include <gtk--/calendar.h>
#include <gtk--/spinbutton.h>

class termsplidial_glade : public Gtk::Dialog
{  
protected:
        
        class Gtk::Calendar *termin_neu;
        class Gtk::SpinButton *menge_neu;
        
        termsplidial_glade();
        
        ~termsplidial_glade();
private:
        virtual void on_okbutton_clicked() = 0;
        virtual void on_cancbutton_clicked() = 0;
};
#endif
