// generated 2004/9/13 10:54:51 CEST by christof@puck.petig-baender.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- Komponenten.glade
// for gtk 2.4.9 and gtkmm 2.4.5
//
// Please modify the corresponding derived classes in ././datewin.hh and././datewin.cc

#ifndef _DATEWIN_GLADE_HH
#  define _DATEWIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/notebook.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/label.h>
#include <gtkmm/calendar.h>

class datewin_glade : public Gtk::Notebook
{  
protected:
        
        class Gtk::Notebook * datewin;
        class Gtk::SpinButton * tag;
        class Gtk::SpinButton * monat;
        class Gtk::SpinButton * jahr;
        class Gtk::Label * datum_label;
        class Gtk::SpinButton * kw_spinbutton;
        class Gtk::SpinButton * jahr_spinbutton;
        class Gtk::Calendar * calendar1;
        
        datewin_glade(GlademmData *gmm_data);
        
        ~datewin_glade();
private:
        virtual void on_activate() = 0;
        virtual void datum_activate() = 0;
        virtual void kw_activate() = 0;
        virtual void on_day_selected() = 0;
        virtual void datum_setzen() = 0;
        virtual void on_datewin_switch_page(GtkNotebookPage *p0, guint p1) = 0;
};
#endif
