// generated 2002/9/25 10:08:11 CEST by christof@puck.petig-baender.de
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gtkmmversion 2.0 Komponenten.glade
// for gtk 2.0.6 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/datewin.cc

#include "config.h"
#include "datewin.hh"
#include <gtkmm/adjustment.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/handlebox.h>
#include <gtkmm/button.h>

datewin_glade::datewin_glade(
)
{  datewin = this;
   
   Gtk::Adjustment *tag_adj = manage(new class Gtk::Adjustment(1, 1, 31, 1, 7, 7));
   tag = manage(new class Gtk::SpinButton(*tag_adj, 1, 0));
   
   Gtk::Label *label2 = manage(new class Gtk::Label("."));
   Gtk::Adjustment *monat_adj = manage(new class Gtk::Adjustment(1, 1, 12, 1, 3, 3));
   monat = manage(new class Gtk::SpinButton(*monat_adj, 1, 0));
   
   Gtk::Label *label3 = manage(new class Gtk::Label("."));
   Gtk::Adjustment *jahr_adj = manage(new class Gtk::Adjustment(2002, 1800, 2100, 1, 10, 10));
   jahr = manage(new class Gtk::SpinButton(*jahr_adj, 1, 0));
   
   Gtk::HBox *hbox9 = manage(new class Gtk::HBox(false, 1));
   datum_label = manage(new class Gtk::Label("Datum"));
   
   Gtk::Adjustment *kw_spinbutton_adj = manage(new class Gtk::Adjustment(1, 1, 56, 1, 4, 4));
   kw_spinbutton = manage(new class Gtk::SpinButton(*kw_spinbutton_adj, 1, 0));
   
   Gtk::Label *label7 = manage(new class Gtk::Label("'"));
   Gtk::Adjustment *jahr_spinbutton_adj = manage(new class Gtk::Adjustment(2002, 1800, 2099, 1, 10, 10));
   jahr_spinbutton = manage(new class Gtk::SpinButton(*jahr_spinbutton_adj, 1, 0));
   
   Gtk::HBox *hbox1 = manage(new class Gtk::HBox(false, 0));
   Gtk::Label *label4 = manage(new class Gtk::Label("Woche"));
   calendar1 = manage(new class Gtk::Calendar());
   
   Gtk::HandleBox *handlebox1 = manage(new class Gtk::HandleBox());
   Gtk::Label *label5 = manage(new class Gtk::Label("Kalender"));
   Gtk::Button *button1 = manage(new class Gtk::Button("Datum setzen"));
   Gtk::Label *label6 = manage(new class Gtk::Label("leer"));
   tag->set_size_request(40,-1);
   tag->set_name("tag");
   tag->set_flags(Gtk::CAN_FOCUS);
   tag->set_update_policy(Gtk::UPDATE_ALWAYS);
   tag->set_numeric(true);
   tag->set_digits(0);
   tag->set_wrap(true);
   tag->set_snap_to_ticks(false);
   label2->set_name("label2");
   label2->set_alignment(0.5,0.5);
   label2->set_padding(0,0);
   label2->set_justify(Gtk::JUSTIFY_CENTER);
   label2->set_line_wrap(false);
   monat->set_size_request(40,-1);
   monat->set_name("monat");
   monat->set_flags(Gtk::CAN_FOCUS);
   monat->set_update_policy(Gtk::UPDATE_ALWAYS);
   monat->set_numeric(true);
   monat->set_digits(0);
   monat->set_wrap(true);
   monat->set_snap_to_ticks(false);
   label3->set_name("label3");
   label3->set_alignment(0.5,0.5);
   label3->set_padding(0,0);
   label3->set_justify(Gtk::JUSTIFY_CENTER);
   label3->set_line_wrap(false);
   jahr->set_size_request(55,-1);
   jahr->set_name("jahr");
   jahr->set_flags(Gtk::CAN_FOCUS);
   jahr->set_update_policy(Gtk::UPDATE_ALWAYS);
   jahr->set_numeric(true);
   jahr->set_digits(0);
   jahr->set_wrap(false);
   jahr->set_snap_to_ticks(false);
   hbox9->set_name("hbox9");
   hbox9->set_border_width(1);
   hbox9->pack_start(*tag, Gtk::SHRINK, 0);
   hbox9->pack_start(*label2, Gtk::SHRINK, 0);
   hbox9->pack_start(*monat, Gtk::SHRINK, 0);
   hbox9->pack_start(*label3, Gtk::SHRINK, 0);
   hbox9->pack_start(*jahr, Gtk::SHRINK, 0);
   datum_label->set_name("datum_label");
   datum_label->set_alignment(0.5,0.5);
   datum_label->set_padding(0,0);
   datum_label->set_justify(Gtk::JUSTIFY_CENTER);
   datum_label->set_line_wrap(false);
   kw_spinbutton->set_name("kw_spinbutton");
   kw_spinbutton->set_flags(Gtk::CAN_FOCUS);
   kw_spinbutton->set_update_policy(Gtk::UPDATE_ALWAYS);
   kw_spinbutton->set_numeric(false);
   kw_spinbutton->set_digits(0);
   kw_spinbutton->set_wrap(false);
   kw_spinbutton->set_snap_to_ticks(false);
   label7->set_name("label7");
   label7->set_alignment(0.5,0.5);
   label7->set_padding(0,0);
   label7->set_justify(Gtk::JUSTIFY_CENTER);
   label7->set_line_wrap(false);
   jahr_spinbutton->set_name("jahr_spinbutton");
   jahr_spinbutton->set_flags(Gtk::CAN_FOCUS);
   jahr_spinbutton->set_update_policy(Gtk::UPDATE_ALWAYS);
   jahr_spinbutton->set_numeric(false);
   jahr_spinbutton->set_digits(0);
   jahr_spinbutton->set_wrap(false);
   jahr_spinbutton->set_snap_to_ticks(false);
   hbox1->set_name("hbox1");
   hbox1->pack_start(*kw_spinbutton);
   hbox1->pack_start(*label7, Gtk::SHRINK, 0);
   hbox1->pack_start(*jahr_spinbutton);
   label4->set_name("label4");
   label4->set_alignment(0.5,0.5);
   label4->set_padding(0,0);
   label4->set_justify(Gtk::JUSTIFY_CENTER);
   label4->set_line_wrap(false);
   calendar1->set_name("calendar1");
   calendar1->set_flags(Gtk::CAN_FOCUS);
   calendar1->display_options(Gtk::CALENDAR_SHOW_HEADING|Gtk::CALENDAR_SHOW_DAY_NAMES|Gtk::CALENDAR_SHOW_WEEK_NUMBERS|Gtk::CALENDAR_WEEK_START_MONDAY);
   handlebox1->set_name("handlebox1");
   handlebox1->set_shadow_type(Gtk::SHADOW_NONE);
   handlebox1->set_handle_position(Gtk::POS_RIGHT);
   handlebox1->set_snap_edge(Gtk::POS_TOP);
   handlebox1->add(*calendar1);
   label5->set_name("label5");
   label5->set_alignment(0.5,0.5);
   label5->set_padding(0,0);
   label5->set_justify(Gtk::JUSTIFY_CENTER);
   label5->set_line_wrap(false);
   button1->set_name("button1");
   button1->set_flags(Gtk::CAN_FOCUS);
   button1->set_relief(Gtk::RELIEF_NORMAL);
   label6->set_name("label6");
   label6->set_alignment(0.5,0.5);
   label6->set_padding(0,0);
   label6->set_justify(Gtk::JUSTIFY_CENTER);
   label6->set_line_wrap(false);
   datewin->set_name("datewin");
   datewin->set_flags(Gtk::CAN_FOCUS);
   datewin->set_show_tabs(true);
   datewin->set_show_border(false);
   datewin->set_tab_pos(Gtk::POS_LEFT);
   datewin->set_scrollable(true);
   datewin->property_tab_hborder().set_value(0);
   datewin->property_tab_vborder().set_value(0);
   datewin->popup_enable();
   datewin->append_page(*hbox9, *datum_label);
   datewin->append_page(*hbox1, *label4);
   datewin->append_page(*handlebox1, *label5);
   datewin->append_page(*button1, *label6);
   tag->show();
   label2->show();
   monat->show();
   label3->show();
   jahr->show();
   hbox9->show();
   datum_label->show();
   kw_spinbutton->show();
   label7->show();
   jahr_spinbutton->show();
   hbox1->show();
   label4->show();
   label5->show();
   button1->show();
   label6->show();
   datewin->show();
   tag->signal_activate().connect(SigC::bind(SigC::slot(*static_cast<class datewin*>(this), &datewin::on_activate), 1), true);
   monat->signal_activate().connect(SigC::bind(SigC::slot(*static_cast<class datewin*>(this), &datewin::on_activate), 2), true);
   jahr->signal_activate().connect(SigC::slot(*static_cast<class datewin*>(this), &datewin::datum_activate), true);
   kw_spinbutton->signal_activate().connect(SigC::slot(*jahr_spinbutton,&Gtk::Widget::grab_focus), true);
   jahr_spinbutton->signal_activate().connect(SigC::slot(*static_cast<class datewin*>(this), &datewin::kw_activate), true);
   calendar1->signal_day_selected().connect(SigC::slot(*static_cast<class datewin*>(this), &datewin::on_day_selected));
   button1->signal_clicked().connect(SigC::slot(*static_cast<class datewin*>(this), &datewin::datum_setzen));
   datewin->signal_switch_page().connect(SigC::slot(*static_cast<class datewin*>(this), &datewin::on_datewin_switch_page), true);
}

datewin_glade::~datewin_glade()
{  
}
