#!/bin/sh

psql $1 <<EOF
SELECT pg_catalog.setval ('ketten_kettid_seq', 5675, true);
SELECT pg_catalog.setval ('prod_changejournal_chid_seq', 44371, true);
SELECT pg_catalog.setval ('schaertabelle_entryid_seq', 211774, true);
EOF
