#!/bin/bash

dropdb testdb
createdb testdb

P="database_tables_init"

for i in \
   $P/artikelstamm \
   $P/artikelzusammensetzung \
   $P/artbez_0_1 \
   $P/artbez_3_1 \
   $P/artbez_3_1000 \
   $P/auftrag \
   $P/auftragentry \
   $P/auftrag_prozess \
   $P/auftragsentryzuordnung \
   $P/einheiten \
   $P/extbezschema \
   $P/ketten \
   $P/ketten_kettid_seq \
   $P/kunden \
   $P/lager_bewegung \
   $P/lastcode \
   $P/problems \
   $P/prod_changejournal \
   $P/prod_changejournal_chid_seq \
   $P/prod_instanz \
   $P/prozesse \
   $P/schaertabelle \
   $P/schaertabelle_entryid_seq \
   $P/rl_inhalt \
   $P/rl_log \
   $P/rohjumbo \
   $P/waehrung \
   $P/webangaben
do

psql testdb -q < $i

done

../../Programme/Instanzen testdb
