#!/bin/bash

export PGHOST=localhost

dropdb testdb
createdb testdb

P="database_tables_init"

for i in \
   artikelbezeichnung \
   artikelstamm \
   artikelzusammensetzung \
   artbez_3_1 \
   artbez_3_1000 \
   artbez_4_1 \
   artbez_5_1 \
   artbez_0_1 \
   artbez_0_1000 \
   artbez_warengruppe \
   auftrag \
   auftragentry \
   auftrag_prozess \
   auftragsentryzuordnung \
   banken \
   einheiten \
   extbezschema \
   global_settings \
   lieferschein \
   lieferscheinentry \
   lieferscheinentryzusatz \
   ketten \
   ketten_kettid_seq \
   kunden \
   lager_bewegung \
   lastcode \
   problems \
   prod_changejournal \
   prod_changejournal_chid_seq \
   prod_instanz \
   prozesse \
   schaertabelle \
   schaertabelle_entryid_seq \
   rechnung_zahlungsart \
   rl_inhalt \
   rl_log \
   rohjumbo \
   waehrung \
   webangaben \
   webang_bindung \
   webang_faeden \
   webang_schuss \
   webang_wiederhol
do

psql testdb -q < $P/$i

done

../../Programme/Instanzen testdb

#psql testdb -c "vacuum analyze"

