#!/bin/bash

dropdb testdb
createdb testdb

P="database_tables_init"

for i in \
   artikelbezeichnung \
   artikelstamm \
   artikelzusammensetzung \
   artbez_0_1 \
   artbez_3_1 \
   artbez_3_1000 \
   auftrag \
   auftragentry \
   auftrag_prozess \
   auftragsentryzuordnung \
   einheiten \
   extbezschema \
   ketten \
   ketten_kettid_seq \
   kunden \
   lager_bewegung \
   lastcode \
   problems \
   prod_changejournal \
   prod_changejournal_chid_seq \
   prod_instanz \
   prozesse \
   schaertabelle \
   schaertabelle_entryid_seq \
   rl_inhalt \
   rl_log \
   rohjumbo \
   waehrung \
   webangaben
do

psql testdb -q < $P/$i

done

../../Programme/Instanzen testdb
