// generated 2001/6/28 10:54:16 MEST by christof@petig.petig.de
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 1.2.9 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in .//simplest.hh and.//simplest.cc

#ifndef _SIMPLEST_GLADE_HH
#  define _SIMPLEST_GLADE_HH

#include <gtk--/window.h>
#include "SimpleTree.hh"

class simplest_glade : public Gtk::Window
{   
protected:
        
        class SimpleTree *treebase;
        
        simplest_glade();
        
        ~simplest_glade();
};
#endif
