// generated 2001/10/25 12:46:52 CEST by christof@puck.petig-baender.de
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 1.2.10 and gtkmm 1.2.7
//
// Please modify the corresponding derived classes in .//simplest.cc

#include "config.h"
#include "simplest.hh"
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/box.h>

simplest_glade::simplest_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *simplest = this;
   Gtk::MenuItem *Beenden = NULL;
   Gtk::Menu *menu1 = manage(new class Gtk::Menu());
   Gtk::MenuItem *Datei = NULL;
   Gtk::MenuBar *menubar1 = manage(new class Gtk::MenuBar());
   treebase = new class SimpleTree(5, 3);
   
   Gtk::VBox *vbox1 = manage(new class Gtk::VBox(false, 0));
   
   menu1->items().push_back(Gtk::Menu_Helpers::MenuElem("Beenden"));
   Beenden = (Gtk::MenuItem *)menu1->items().back();
   
   
   menubar1->items().push_back(Gtk::Menu_Helpers::MenuElem("Datei", *menu1));
   Datei = (Gtk::MenuItem *)menubar1->items().back();
   vbox1->pack_start(*menubar1, false, true, 0);
   vbox1->pack_start(*treebase);
   simplest->set_title("simplest");
   simplest->set_policy(true, true, false);
   simplest->add(*vbox1);
   Beenden->show();
   menu1->show();
   Datei->show();
   menubar1->show();
   treebase->show();
   vbox1->show();
   simplest->show();
   Beenden->activate.connect(SigC::slot(static_cast<class simplest*>(this), &simplest::on_Beenden_activate));
}

simplest_glade::~simplest_glade()
{   delete treebase;
}
