// generated 2001/10/25 12:46:53 CEST by christof@puck.petig-baender.de
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- tree.glade
// for gtk 1.2.10 and gtkmm 1.2.7
//
// Please modify the corresponding derived classes in .//with_class.cc

#include "config.h"
#include "with_class.hh"
#include <gtk--/list.h>
#include <gtk--/menu.h>
#include <gtk--/menubar.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/box.h>

with_class_glade::with_class_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *with_class = this;
   Gtk::MenuItem *menuitem2 = NULL;
   Gtk::Menu *menu2 = manage(new class Gtk::Menu());
   Gtk::MenuItem *menuitem1 = NULL;
   Gtk::MenuBar *menubar2 = manage(new class Gtk::MenuBar());
   treebase = new class SimpleTree(6, 5);
   
   Gtk::ScrolledWindow *scrolledwindow1 = manage(new class Gtk::ScrolledWindow());
   Gtk::VBox *vbox2 = manage(new class Gtk::VBox(false, 0));
   
   menu2->items().push_back(Gtk::Menu_Helpers::MenuElem("Beenden"));
   menuitem2 = (Gtk::MenuItem *)menu2->items().back();
   
   
   menubar2->items().push_back(Gtk::Menu_Helpers::MenuElem("Datei", *menu2));
   menuitem1 = (Gtk::MenuItem *)menubar2->items().back();
   scrolledwindow1->set_policy(GTK_POLICY_ALWAYS, GTK_POLICY_ALWAYS);
   scrolledwindow1->add(*treebase);
   vbox2->pack_start(*menubar2, false, true, 0);
   vbox2->pack_start(*scrolledwindow1);
   with_class->set_title("with_class");
   with_class->set_policy(true, true, false);
   with_class->add(*vbox2);
   menuitem2->show();
   menu2->show();
   menuitem1->show();
   menubar2->show();
   treebase->show();
   scrolledwindow1->show();
   vbox2->show();
   with_class->show();
   menuitem2->activate.connect(SigC::slot(static_cast<class with_class*>(this), &with_class::on_Beenden_activate));
}

with_class_glade::~with_class_glade()
{   delete treebase;
}
